<?php

namespace App\Console\Commands;

use App\Models\Country;
use Illuminate\Console\Command;

class SeedCountries extends Command
{
    protected $signature = 'countries:seed';
    protected $description = 'Seed the countries table with all UN member states';

    public function handle(): int
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'phone_code' => '+93', 'is_active' => false],
            ['name' => 'Albania', 'code' => 'AL', 'phone_code' => '+355', 'is_active' => false],
            ['name' => 'Algeria', 'code' => 'DZ', 'phone_code' => '+213', 'is_active' => false],
            ['name' => 'Andorra', 'code' => 'AD', 'phone_code' => '+376', 'is_active' => false],
            ['name' => 'Angola', 'code' => 'AO', 'phone_code' => '+244', 'is_active' => false],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'phone_code' => '+1268', 'is_active' => false],
            ['name' => 'Argentina', 'code' => 'AR', 'phone_code' => '+54', 'is_active' => false],
            ['name' => 'Armenia', 'code' => 'AM', 'phone_code' => '+374', 'is_active' => false],
            ['name' => 'Australia', 'code' => 'AU', 'phone_code' => '+61', 'is_active' => false],
            ['name' => 'Austria', 'code' => 'AT', 'phone_code' => '+43', 'is_active' => false],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'phone_code' => '+994', 'is_active' => false],
            ['name' => 'Bahamas', 'code' => 'BS', 'phone_code' => '+1242', 'is_active' => false],
            ['name' => 'Bahrain', 'code' => 'BH', 'phone_code' => '+973', 'is_active' => false],
            ['name' => 'Bangladesh', 'code' => 'BD', 'phone_code' => '+880', 'is_active' => false],
            ['name' => 'Barbados', 'code' => 'BB', 'phone_code' => '+1246', 'is_active' => false],
            ['name' => 'Belarus', 'code' => 'BY', 'phone_code' => '+375', 'is_active' => false],
            ['name' => 'Belgium', 'code' => 'BE', 'phone_code' => '+32', 'is_active' => false],
            ['name' => 'Belize', 'code' => 'BZ', 'phone_code' => '+501', 'is_active' => false],
            ['name' => 'Benin', 'code' => 'BJ', 'phone_code' => '+229', 'is_active' => false],
            ['name' => 'Bhutan', 'code' => 'BT', 'phone_code' => '+975', 'is_active' => false],
            ['name' => 'Bolivia', 'code' => 'BO', 'phone_code' => '+591', 'is_active' => false],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'phone_code' => '+387', 'is_active' => false],
            ['name' => 'Botswana', 'code' => 'BW', 'phone_code' => '+267', 'is_active' => true],
            ['name' => 'Brazil', 'code' => 'BR', 'phone_code' => '+55', 'is_active' => false],
            ['name' => 'Brunei', 'code' => 'BN', 'phone_code' => '+673', 'is_active' => false],
            ['name' => 'Bulgaria', 'code' => 'BG', 'phone_code' => '+359', 'is_active' => false],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'phone_code' => '+226', 'is_active' => false],
            ['name' => 'Burundi', 'code' => 'BI', 'phone_code' => '+257', 'is_active' => true],
            ['name' => 'Cabo Verde', 'code' => 'CV', 'phone_code' => '+238', 'is_active' => false],
            ['name' => 'Cambodia', 'code' => 'KH', 'phone_code' => '+855', 'is_active' => false],
            ['name' => 'Cameroon', 'code' => 'CM', 'phone_code' => '+237', 'is_active' => false],
            ['name' => 'Canada', 'code' => 'CA', 'phone_code' => '+1', 'is_active' => false],
            ['name' => 'Central African Republic', 'code' => 'CF', 'phone_code' => '+236', 'is_active' => false],
            ['name' => 'Chad', 'code' => 'TD', 'phone_code' => '+235', 'is_active' => false],
            ['name' => 'Chile', 'code' => 'CL', 'phone_code' => '+56', 'is_active' => false],
            ['name' => 'China', 'code' => 'CN', 'phone_code' => '+86', 'is_active' => false],
            ['name' => 'Colombia', 'code' => 'CO', 'phone_code' => '+57', 'is_active' => false],
            ['name' => 'Comoros', 'code' => 'KM', 'phone_code' => '+269', 'is_active' => false],
            ['name' => 'Congo', 'code' => 'CG', 'phone_code' => '+242', 'is_active' => false],
            ['name' => 'Costa Rica', 'code' => 'CR', 'phone_code' => '+506', 'is_active' => false],
            ['name' => 'Croatia', 'code' => 'HR', 'phone_code' => '+385', 'is_active' => false],
            ['name' => 'Cuba', 'code' => 'CU', 'phone_code' => '+53', 'is_active' => false],
            ['name' => 'Cyprus', 'code' => 'CY', 'phone_code' => '+357', 'is_active' => false],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'phone_code' => '+420', 'is_active' => false],
            ['name' => 'Denmark', 'code' => 'DK', 'phone_code' => '+45', 'is_active' => false],
            ['name' => 'Djibouti', 'code' => 'DJ', 'phone_code' => '+253', 'is_active' => false],
            ['name' => 'Dominica', 'code' => 'DM', 'phone_code' => '+1767', 'is_active' => false],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'phone_code' => '+1', 'is_active' => false],
            ['name' => 'DR Congo', 'code' => 'CD', 'phone_code' => '+243', 'is_active' => true],
            ['name' => 'Ecuador', 'code' => 'EC', 'phone_code' => '+593', 'is_active' => false],
            ['name' => 'Egypt', 'code' => 'EG', 'phone_code' => '+20', 'is_active' => false],
            ['name' => 'El Salvador', 'code' => 'SV', 'phone_code' => '+503', 'is_active' => false],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'phone_code' => '+240', 'is_active' => false],
            ['name' => 'Eritrea', 'code' => 'ER', 'phone_code' => '+291', 'is_active' => false],
            ['name' => 'Estonia', 'code' => 'EE', 'phone_code' => '+372', 'is_active' => false],
            ['name' => 'Eswatini', 'code' => 'SZ', 'phone_code' => '+268', 'is_active' => false],
            ['name' => 'Ethiopia', 'code' => 'ET', 'phone_code' => '+251', 'is_active' => false],
            ['name' => 'Fiji', 'code' => 'FJ', 'phone_code' => '+679', 'is_active' => false],
            ['name' => 'Finland', 'code' => 'FI', 'phone_code' => '+358', 'is_active' => false],
            ['name' => 'France', 'code' => 'FR', 'phone_code' => '+33', 'is_active' => false],
            ['name' => 'Gabon', 'code' => 'GA', 'phone_code' => '+241', 'is_active' => false],
            ['name' => 'Gambia', 'code' => 'GM', 'phone_code' => '+220', 'is_active' => false],
            ['name' => 'Georgia', 'code' => 'GE', 'phone_code' => '+995', 'is_active' => false],
            ['name' => 'Germany', 'code' => 'DE', 'phone_code' => '+49', 'is_active' => false],
            ['name' => 'Ghana', 'code' => 'GH', 'phone_code' => '+233', 'is_active' => true],
            ['name' => 'Greece', 'code' => 'GR', 'phone_code' => '+30', 'is_active' => false],
            ['name' => 'Grenada', 'code' => 'GD', 'phone_code' => '+1473', 'is_active' => false],
            ['name' => 'Guatemala', 'code' => 'GT', 'phone_code' => '+502', 'is_active' => false],
            ['name' => 'Guinea', 'code' => 'GN', 'phone_code' => '+224', 'is_active' => false],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'phone_code' => '+245', 'is_active' => false],
            ['name' => 'Guyana', 'code' => 'GY', 'phone_code' => '+592', 'is_active' => false],
            ['name' => 'Haiti', 'code' => 'HT', 'phone_code' => '+509', 'is_active' => false],
            ['name' => 'Honduras', 'code' => 'HN', 'phone_code' => '+504', 'is_active' => false],
            ['name' => 'Hungary', 'code' => 'HU', 'phone_code' => '+36', 'is_active' => false],
            ['name' => 'Iceland', 'code' => 'IS', 'phone_code' => '+354', 'is_active' => false],
            ['name' => 'India', 'code' => 'IN', 'phone_code' => '+91', 'is_active' => false],
            ['name' => 'Indonesia', 'code' => 'ID', 'phone_code' => '+62', 'is_active' => false],
            ['name' => 'Iran', 'code' => 'IR', 'phone_code' => '+98', 'is_active' => false],
            ['name' => 'Iraq', 'code' => 'IQ', 'phone_code' => '+964', 'is_active' => false],
            ['name' => 'Ireland', 'code' => 'IE', 'phone_code' => '+353', 'is_active' => false],
            ['name' => 'Israel', 'code' => 'IL', 'phone_code' => '+972', 'is_active' => false],
            ['name' => 'Italy', 'code' => 'IT', 'phone_code' => '+39', 'is_active' => false],
            ['name' => 'Ivory Coast', 'code' => 'CI', 'phone_code' => '+225', 'is_active' => false],
            ['name' => 'Jamaica', 'code' => 'JM', 'phone_code' => '+1876', 'is_active' => false],
            ['name' => 'Japan', 'code' => 'JP', 'phone_code' => '+81', 'is_active' => false],
            ['name' => 'Jordan', 'code' => 'JO', 'phone_code' => '+962', 'is_active' => false],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'phone_code' => '+7', 'is_active' => false],
            ['name' => 'Kenya', 'code' => 'KE', 'phone_code' => '+254', 'is_active' => true],
            ['name' => 'Kiribati', 'code' => 'KI', 'phone_code' => '+686', 'is_active' => false],
            ['name' => 'Kuwait', 'code' => 'KW', 'phone_code' => '+965', 'is_active' => false],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'phone_code' => '+996', 'is_active' => false],
            ['name' => 'Laos', 'code' => 'LA', 'phone_code' => '+856', 'is_active' => false],
            ['name' => 'Latvia', 'code' => 'LV', 'phone_code' => '+371', 'is_active' => false],
            ['name' => 'Lebanon', 'code' => 'LB', 'phone_code' => '+961', 'is_active' => false],
            ['name' => 'Lesotho', 'code' => 'LS', 'phone_code' => '+266', 'is_active' => false],
            ['name' => 'Liberia', 'code' => 'LR', 'phone_code' => '+231', 'is_active' => false],
            ['name' => 'Libya', 'code' => 'LY', 'phone_code' => '+218', 'is_active' => false],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'phone_code' => '+423', 'is_active' => false],
            ['name' => 'Lithuania', 'code' => 'LT', 'phone_code' => '+370', 'is_active' => false],
            ['name' => 'Luxembourg', 'code' => 'LU', 'phone_code' => '+352', 'is_active' => false],
            ['name' => 'Madagascar', 'code' => 'MG', 'phone_code' => '+261', 'is_active' => false],
            ['name' => 'Malawi', 'code' => 'MW', 'phone_code' => '+265', 'is_active' => false],
            ['name' => 'Malaysia', 'code' => 'MY', 'phone_code' => '+60', 'is_active' => false],
            ['name' => 'Maldives', 'code' => 'MV', 'phone_code' => '+960', 'is_active' => false],
            ['name' => 'Mali', 'code' => 'ML', 'phone_code' => '+223', 'is_active' => false],
            ['name' => 'Malta', 'code' => 'MT', 'phone_code' => '+356', 'is_active' => false],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'phone_code' => '+692', 'is_active' => false],
            ['name' => 'Mauritania', 'code' => 'MR', 'phone_code' => '+222', 'is_active' => false],
            ['name' => 'Mauritius', 'code' => 'MU', 'phone_code' => '+230', 'is_active' => false],
            ['name' => 'Mexico', 'code' => 'MX', 'phone_code' => '+52', 'is_active' => false],
            ['name' => 'Micronesia', 'code' => 'FM', 'phone_code' => '+691', 'is_active' => false],
            ['name' => 'Moldova', 'code' => 'MD', 'phone_code' => '+373', 'is_active' => false],
            ['name' => 'Monaco', 'code' => 'MC', 'phone_code' => '+377', 'is_active' => false],
            ['name' => 'Mongolia', 'code' => 'MN', 'phone_code' => '+976', 'is_active' => false],
            ['name' => 'Montenegro', 'code' => 'ME', 'phone_code' => '+382', 'is_active' => false],
            ['name' => 'Morocco', 'code' => 'MA', 'phone_code' => '+212', 'is_active' => false],
            ['name' => 'Mozambique', 'code' => 'MZ', 'phone_code' => '+258', 'is_active' => false],
            ['name' => 'Myanmar', 'code' => 'MM', 'phone_code' => '+95', 'is_active' => false],
            ['name' => 'Namibia', 'code' => 'NA', 'phone_code' => '+264', 'is_active' => false],
            ['name' => 'Nauru', 'code' => 'NR', 'phone_code' => '+674', 'is_active' => false],
            ['name' => 'Nepal', 'code' => 'NP', 'phone_code' => '+977', 'is_active' => false],
            ['name' => 'Netherlands', 'code' => 'NL', 'phone_code' => '+31', 'is_active' => false],
            ['name' => 'New Zealand', 'code' => 'NZ', 'phone_code' => '+64', 'is_active' => false],
            ['name' => 'Nicaragua', 'code' => 'NI', 'phone_code' => '+505', 'is_active' => false],
            ['name' => 'Niger', 'code' => 'NE', 'phone_code' => '+227', 'is_active' => false],
            ['name' => 'Nigeria', 'code' => 'NG', 'phone_code' => '+234', 'is_active' => true],
            ['name' => 'North Korea', 'code' => 'KP', 'phone_code' => '+850', 'is_active' => false],
            ['name' => 'North Macedonia', 'code' => 'MK', 'phone_code' => '+389', 'is_active' => false],
            ['name' => 'Norway', 'code' => 'NO', 'phone_code' => '+47', 'is_active' => false],
            ['name' => 'Oman', 'code' => 'OM', 'phone_code' => '+968', 'is_active' => false],
            ['name' => 'Pakistan', 'code' => 'PK', 'phone_code' => '+92', 'is_active' => false],
            ['name' => 'Palau', 'code' => 'PW', 'phone_code' => '+680', 'is_active' => false],
            ['name' => 'Palestine', 'code' => 'PS', 'phone_code' => '+970', 'is_active' => false],
            ['name' => 'Panama', 'code' => 'PA', 'phone_code' => '+507', 'is_active' => false],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'phone_code' => '+675', 'is_active' => false],
            ['name' => 'Paraguay', 'code' => 'PY', 'phone_code' => '+595', 'is_active' => false],
            ['name' => 'Peru', 'code' => 'PE', 'phone_code' => '+51', 'is_active' => false],
            ['name' => 'Philippines', 'code' => 'PH', 'phone_code' => '+63', 'is_active' => false],
            ['name' => 'Poland', 'code' => 'PL', 'phone_code' => '+48', 'is_active' => false],
            ['name' => 'Portugal', 'code' => 'PT', 'phone_code' => '+351', 'is_active' => false],
            ['name' => 'Qatar', 'code' => 'QA', 'phone_code' => '+974', 'is_active' => false],
            ['name' => 'Romania', 'code' => 'RO', 'phone_code' => '+40', 'is_active' => false],
            ['name' => 'Russia', 'code' => 'RU', 'phone_code' => '+7', 'is_active' => false],
            ['name' => 'Rwanda', 'code' => 'RW', 'phone_code' => '+250', 'is_active' => true],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'phone_code' => '+1869', 'is_active' => false],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'phone_code' => '+1758', 'is_active' => false],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'phone_code' => '+1784', 'is_active' => false],
            ['name' => 'Samoa', 'code' => 'WS', 'phone_code' => '+685', 'is_active' => false],
            ['name' => 'San Marino', 'code' => 'SM', 'phone_code' => '+378', 'is_active' => false],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'phone_code' => '+239', 'is_active' => false],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'phone_code' => '+966', 'is_active' => false],
            ['name' => 'Senegal', 'code' => 'SN', 'phone_code' => '+221', 'is_active' => false],
            ['name' => 'Serbia', 'code' => 'RS', 'phone_code' => '+381', 'is_active' => false],
            ['name' => 'Seychelles', 'code' => 'SC', 'phone_code' => '+248', 'is_active' => false],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'phone_code' => '+232', 'is_active' => false],
            ['name' => 'Singapore', 'code' => 'SG', 'phone_code' => '+65', 'is_active' => false],
            ['name' => 'Slovakia', 'code' => 'SK', 'phone_code' => '+421', 'is_active' => false],
            ['name' => 'Slovenia', 'code' => 'SI', 'phone_code' => '+386', 'is_active' => false],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'phone_code' => '+677', 'is_active' => false],
            ['name' => 'Somalia', 'code' => 'SO', 'phone_code' => '+252', 'is_active' => false],
            ['name' => 'South Africa', 'code' => 'ZA', 'phone_code' => '+27', 'is_active' => true],
            ['name' => 'South Korea', 'code' => 'KR', 'phone_code' => '+82', 'is_active' => false],
            ['name' => 'South Sudan', 'code' => 'SS', 'phone_code' => '+211', 'is_active' => false],
            ['name' => 'Spain', 'code' => 'ES', 'phone_code' => '+34', 'is_active' => false],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'phone_code' => '+94', 'is_active' => false],
            ['name' => 'Sudan', 'code' => 'SD', 'phone_code' => '+249', 'is_active' => false],
            ['name' => 'Suriname', 'code' => 'SR', 'phone_code' => '+597', 'is_active' => false],
            ['name' => 'Sweden', 'code' => 'SE', 'phone_code' => '+46', 'is_active' => false],
            ['name' => 'Switzerland', 'code' => 'CH', 'phone_code' => '+41', 'is_active' => false],
            ['name' => 'Syria', 'code' => 'SY', 'phone_code' => '+963', 'is_active' => false],
            ['name' => 'Taiwan', 'code' => 'TW', 'phone_code' => '+886', 'is_active' => false],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'phone_code' => '+992', 'is_active' => false],
            ['name' => 'Tanzania', 'code' => 'TZ', 'phone_code' => '+255', 'is_active' => true],
            ['name' => 'Thailand', 'code' => 'TH', 'phone_code' => '+66', 'is_active' => false],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'phone_code' => '+670', 'is_active' => false],
            ['name' => 'Togo', 'code' => 'TG', 'phone_code' => '+228', 'is_active' => false],
            ['name' => 'Tonga', 'code' => 'TO', 'phone_code' => '+676', 'is_active' => false],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'phone_code' => '+1868', 'is_active' => false],
            ['name' => 'Tunisia', 'code' => 'TN', 'phone_code' => '+216', 'is_active' => false],
            ['name' => 'Turkey', 'code' => 'TR', 'phone_code' => '+90', 'is_active' => false],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'phone_code' => '+993', 'is_active' => false],
            ['name' => 'Tuvalu', 'code' => 'TV', 'phone_code' => '+688', 'is_active' => false],
            ['name' => 'Uganda', 'code' => 'UG', 'phone_code' => '+256', 'is_active' => true],
            ['name' => 'Ukraine', 'code' => 'UA', 'phone_code' => '+380', 'is_active' => false],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'phone_code' => '+971', 'is_active' => false],
            ['name' => 'United Kingdom', 'code' => 'GB', 'phone_code' => '+44', 'is_active' => false],
            ['name' => 'United States', 'code' => 'US', 'phone_code' => '+1', 'is_active' => false],
            ['name' => 'Uruguay', 'code' => 'UY', 'phone_code' => '+598', 'is_active' => false],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'phone_code' => '+998', 'is_active' => false],
            ['name' => 'Vanuatu', 'code' => 'VU', 'phone_code' => '+678', 'is_active' => false],
            ['name' => 'Vatican City', 'code' => 'VA', 'phone_code' => '+379', 'is_active' => false],
            ['name' => 'Venezuela', 'code' => 'VE', 'phone_code' => '+58', 'is_active' => false],
            ['name' => 'Vietnam', 'code' => 'VN', 'phone_code' => '+84', 'is_active' => false],
            ['name' => 'Yemen', 'code' => 'YE', 'phone_code' => '+967', 'is_active' => false],
            ['name' => 'Zambia', 'code' => 'ZM', 'phone_code' => '+260', 'is_active' => true],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'phone_code' => '+263', 'is_active' => true],
        ];

        $count = 0;
        foreach ($countries as $country) {
            $country['flag_url'] = config('app-custom.flag_cdn_url') . "/{$country['code']}.png";
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
            $count++;
        }

        $this->info("Seeded {$count} countries.");

        return self::SUCCESS;
    }
}
