import {
    ArrowLeftRight,
    CircleDollarSign,
    FileText,
    Globe,
    LifeBuoy,
    Settings,
    ShieldCheck,
    Coins,
    CreditCard,
    Megaphone,
    BarChart3,
    TrendingUp,
    Star,
} from "lucide-vue-next";

export const menu = [
    { label: "Transfers", icon: ArrowLeftRight, to: "/transfers" },
    { label: "Users", icon: ShieldCheck, to: "/users" },
    { label: "Countries", icon: Globe, to: "/countries" },
    { label: "Currencies", icon: CircleDollarSign, to: "/currencies" },
    { label: "Assets", icon: Coins, to: "/assets" },
    { label: "Payment Methods", icon: CreditCard, to: "/payment-methods" },
    { label: "Trades", icon: ArrowLeftRight, to: "/trades" },
    { label: "Ads", icon: Megaphone, to: "/ads" },
    { label: "Fees", icon: Coins, to: "/platform-fees" },
    { label: "Prices", icon: TrendingUp, to: "/reference-prices" },
    { label: "Revenue", icon: BarChart3, to: "/revenue" },
    { label: "Reports", icon: FileText, to: "/reports" },
    { label: "Ratings", icon: Star, to: "/ratings" },
    { label: "Announcements", icon: Megaphone, to: "/announcements" },
    { label: "Support", icon: LifeBuoy, to: "/support" },
    { label: "Settings", icon: Settings, to: "/settings" },
];
